name: "Setup Node.js Environment"
description: "Setup Node.js with npm caching for CI/CD workflows"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
    default: "20"
  cache:
    description: "Package manager to cache"
    required: false
    default: "npm"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: bash
      run: npm ci
